export const roomPhoto: Record<string, string> = {
  SINGLE: "/media/rooms/single.webp",
  SMALL_SUITE: "/media/rooms/small-suite.webp",
  STANDARD_SUITE: "/media/rooms/standard-suite.webp",
  LARGE_SUITE_SINGLE: "/media/rooms/large-single.webp",
  APT_SINGLE: "/media/rooms/apt-single.webp",
  LARGE_SUITE_DOUBLE: "/media/rooms/large-double.webp",
  APT_DOUBLE: "/media/rooms/apt-double.webp",
};

export const galleryPhotos: { src: string }[] = [
  { src: "/media/gallery/01.webp" },
  { src: "/media/gallery/03.webp" },
  { src: "/media/gallery/05.webp" },
  { src: "/media/gallery/06.webp" },
  { src: "/media/gallery/07.webp" },
  { src: "/media/gallery/08.webp" },
  { src: "/media/gallery/09.webp" },
  { src: "/media/gallery/11.webp" },
  { src: "/media/gallery/13.webp" },
  { src: "/media/gallery/14.webp" },
  { src: "/media/gallery/16.webp" },
  { src: "/media/gallery/19.webp" },
  { src: "/media/gallery/20.webp" },
  { src: "/media/gallery/21.webp" },
  { src: "/media/gallery/22.webp" },
  { src: "/media/gallery/23.webp" },
  { src: "/media/gallery/24.webp" },
  { src: "/media/gallery/25.webp" },
  { src: "/media/gallery/26.webp" },
  { src: "/media/gallery/27.webp" },
  { src: "/media/gallery/28.webp" },
  { src: "/media/gallery/29.webp" },
  { src: "/media/gallery/30.webp" },
  { src: "/media/gallery/31.webp" },
  { src: "/media/gallery/32.webp" },
  { src: "/media/gallery/33.webp" },
  { src: "/media/gallery/34.webp" },
  { src: "/media/gallery/35.webp" },
  { src: "/media/gallery/36.webp" },
  { src: "/media/gallery/37.webp" },
  { src: "/media/gallery/38.webp" },
  { src: "/media/gallery/39.webp" },
];
